### ISSUE TITLE
Error when running ensemble.py

### ISSUE THREAD

**Issue by Shujian2015** [rdcolema/nc-fish-classification#4]
Thanks for this great code! I have got this error when I run ensemble_model.py (copied code from ensemble_model.ipynb) on AWS. I use theano as backend and run on Tesla k80. 

`----Predicting on vggbn model...
/usr/lib/python3.4/dist-packages/Keras-1.2.2-py3.4.egg/keras/layers/core.py:622: UserWarning: `output_shape` argument not specified for layer lambda_3 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 3, 270, 480)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
Found 0 images belonging to 0 classes.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/dist-packages/Keras-1.2.2-py3.4.egg/keras/engine/training.py", line 429, in data_generator_task
    generator_output = next(self._generator)
  File "/usr/lib/python3.4/dist-packages/Keras-1.2.2-py3.4.egg/keras/preprocessing/image.py", line 662, in __next__
    return self.next(*args, **kwargs)
  File "/usr/lib/python3.4/dist-packages/Keras-1.2.2-py3.4.egg/keras/preprocessing/image.py", line 822, in next
    index_array, current_index, current_batch_size = next(self.index_generator)
  File "/usr/lib/python3.4/dist-packages/Keras-1.2.2-py3.4.egg/keras/preprocessing/image.py", line 645, in _flow_index
    current_index = (self.batch_index * batch_size) % n
ZeroDivisionError: integer division or modulo by zero

Traceback (most recent call last):
  File "ensemble_model.py", line 164, in <module>
    predictions, filenames = test(model_paths)
  File "ensemble_model.py", line 152, in test
    pred, filenames = parent.test(test_path, nb_test_samples, aug=nb_aug)
  File "/home/ec2-user/kaggle/fish/models.py", line 136, in test
    return self.model.predict_generator(test_gen, val_samples=nb_test_samples), test_gen.filenames
  File "/usr/lib/python3.4/dist-packages/Keras-1.2.2-py3.4.egg/keras/models.py", line 1012, in predict_generator
    pickle_safe=pickle_safe)
  File "/usr/lib/python3.4/dist-packages/Keras-1.2.2-py3.4.egg/keras/engine/training.py", line 1763, in predict_generator
    outs = self.predict_on_batch(x)
  File "/usr/lib/python3.4/dist-packages/Keras-1.2.2-py3.4.egg/keras/engine/training.py", line 1371, in predict_on_batch
    self.internal_input_shapes)
  File "/usr/lib/python3.4/dist-packages/Keras-1.2.2-py3.4.egg/keras/engine/training.py", line 85, in standardize_input_data
    'Found: ' + str(data)[:200] + '...')
TypeError: Error when checking : data should be a Numpy array, or list/dict of Numpy arrays. Found: None...
`

**Comment by rdcolema** [comment]
Hey Shujian2015, looks like the data generator isn't finding any images -- how is your data directory structured?

**Comment by Shujian2015** [comment]
Hi, Robert, thanks for your quick response!

My directory is like this:

   .
   |-bb_annotations
   |-data
   |---data
   |---__MACOSX
   |-----train
   |---models
   |---submissions
   |---test
   |---train
   |-----ALB
   |-----BET
   |-----DOL
   |-----LAG
   |-----NoF
   |-----OTHER
   |-----SHARK
   |-----YFT
   |---train_full
   |-----ALB
   |-----BET
   |-----DOL
   |-----LAG
   |-----NoF
   |-----OTHER
   |-----SHARK
   |-----YFT
   |---valid
   |-----ALB
   |-----BET
   |-----DOL
   |-----LAG
   |-----NoF
   |-----OTHER
   |-----SHARK
   |-----YFT
   |-models
   |-__pycache__
   |-submissions

**Comment by rdcolema** [comment]
Keras' `flow_from_directory` function looks for images in subdirectories, so if it's not finding any test images to predict on, i'm guessing your images are located in "/test/" rather than in "/test/test_stg1/" (which is how I have my directory set up). Basically there just needs to be another directory between "/test/" and your actual images, and then the generator should find them.

**Comment by Shujian2015** [comment]
Thanks a lot, Robert! The code now works.
